---
title: "Experimenting with the collapse package"
author: "Keith McNulty"
date: "15/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(summarise.inform = FALSE)
```

Download a 500k row dataset on San Francisco crime incidents.

```{r}
options(timeout = 300)
data <- read.csv(
  "https://data.sfgov.org/api/views/tmnf-yvry/rows.csv?accessType=DOWNLOAD", 
  nrows = 500000
)
```

Calculate the average number of incidents per day using `dplyr`.

```{r}
library(dplyr)

average_count_daily1 <- function(...) {
  data |> 
    dplyr::select(DayOfWeek, Date, IncidntNum) |> 
    dplyr::group_by(DayOfWeek, Date) |> 
    dplyr::summarise(sum = n(), ...) |>
    dplyr::group_by(DayOfWeek) |>
    dplyr::summarise(mean(sum), ...)
}

average_count_daily1(.groups = "drop")
```


Now do the same calculation directly using `collapse` verbs.

```{r}
library(collapse)

average_count_daily2 <- function() {
  data |> 
    fselect(DayOfWeek, Date, IncidntNum) |> 
    fgroup_by(DayOfWeek, Date) |> 
    fnobs() |> 
    fselect(DayOfWeek, IncidntNum) |> 
    fgroup_by(DayOfWeek) |> 
    fmean()
}

average_count_daily2()
```

Benchmark speed across 100 runs.

```{r}
microbenchmark::microbenchmark(
  average_count_daily1(),
  average_count_daily2(),
  times = 100)
```


